### ISSUE TITLE
I invite you to participate this conversation about Open Source autorouters in EEvBlog

### ISSUE THREAD

**Issue by timofonic** [vygr/C-PCB#1]
Hello.

Thanks a lot for investing your efforts in this project. It looks very promising!

One of the missing features if Open Source EDA software is a good autorouters. Despite many attempts, all of them were flawed in important features. FreeRouting looked promising (despite about being written in Java), but got practically taken down by Zuken.

I would like you to participate in this forum thread. Your can explain about your project, your personal goals and what's your opinion about both propietary and Open Source autorouters.

http://www.eevblog.com/forum/index.php?topic=53108.0

Kind regards.

**Comment by vygr** [comment]
Thanks, I have joined the forum !

Chris
