### ISSUE TITLE
Are you interested in this project? Any news?

### ISSUE THREAD

**Issue by timofonic** [vygr/C-PCB#2]
Hello.

As a FOSS enthusiast and electronics student, I was very excited to see your project. Maybe you're busy, but your project looked really interesting.

Are you considering to resume back your efforts? Did you try to cooperate with FOSS EDA software such as gEDA and KiCad?

Kind regards.

**Comment by vygr** [comment]
I'm sure interested, I wouldn't have done the project otherwise. :)

I am however in full time work at the moment and don't have a lot of spare time to code on this. I did it in the hope that somebody might have picked it up and turned it into a plugin for KiCad etc.

Chris

**Comment by timofonic** [comment]
No problem! Real life is there, I understand it!

FYI, there's another project by @StefanSalewski with similar goals but done in Ruby:

https://github.com/StefanSalewski/Ruby-PCB-Router
http://ssalewski.de/Router.html.en

What about some kind of collaboration? :D
